/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteRouteImport } from './routes/_dash/route'
import { Route as DashIndexRouteImport } from './routes/_dash/index'
import { Route as DashStatsRouteImport } from './routes/_dash/stats'
import { Route as DashEventsRouteImport } from './routes/_dash/events'

const DashRouteRoute = DashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashStatsRoute = DashStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashEventsRoute = DashEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/events': typeof DashEventsRoute
  '/stats': typeof DashStatsRoute
}
export interface FileRoutesByTo {
  '/events': typeof DashEventsRoute
  '/stats': typeof DashStatsRoute
  '/': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteRouteWithChildren
  '/_dash/events': typeof DashEventsRoute
  '/_dash/stats': typeof DashStatsRoute
  '/_dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/events' | '/stats' | '/'
  id: '__root__' | '/_dash' | '/_dash/events' | '/_dash/stats' | '/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRouteRoute: typeof DashRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/stats': {
      id: '/_dash/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof DashStatsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/events': {
      id: '/_dash/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DashEventsRouteImport
      parentRoute: typeof DashRouteRoute
    }
  }
}

interface DashRouteRouteChildren {
  DashEventsRoute: typeof DashEventsRoute
  DashStatsRoute: typeof DashStatsRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashEventsRoute: DashEventsRoute,
  DashStatsRoute: DashStatsRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashRouteRoute: DashRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
