#!/usr/bin/env bash
#
# Parcel21 × rgb-sandbox integration runner.
#
# Produces a REAL RGB consignment using the rgb-sandbox regtest demo, but delivers it over
# Parcel21/Nostr instead of the sandbox's `cp`. It does this by generating a patched copy of
# the sandbox's demo.sh (`demo-parcel21.sh`) where the single consignment-copy line:
#
#     _trace cp {"$send_data","$rcpt_data"}/"$CONSIGNMENT"
#
# is replaced by a call to our harness (client/scripts/rgb-e2e.ts), which gift-wraps the real
# consignment, publishes it to the relay, receives + integrity-checks it on the other side, and
# writes it into the recipient's data dir. The sandbox then validates + broadcasts + accepts the
# delivered file exactly as before — proving a real RGB transfer settled with Parcel21 as the
# transport.
#
# Requirements: Docker running, the relay listening (default ws://127.0.0.1:7777), and the
# sandbox's rgb/bp CLIs already installed (they are, under rgb-sandbox/{rgb-cmd,bp-wallet}).
#
# Usage:  PARCEL21_RELAY=ws://127.0.0.1:7777 bash integration/run.sh [scenario]
#         scenario defaults to 100 (single blinded transfer, broadcast+mine).

set -uo pipefail

SANDBOX="${PARCEL21_SANDBOX:-/Users/nicholaschiarulli/RGB/rgb-sandbox}"
CLIENT="${PARCEL21_CLIENT:-/Users/nicholaschiarulli/RGB/parcel21-protocol/client}"
RELAY="${PARCEL21_RELAY:-ws://127.0.0.1:7777}"
SCENARIO="${1:-100}"

SRC="$SANDBOX/demo.sh"
OUT="$SANDBOX/demo-parcel21.sh"

[ -f "$SRC" ] || { echo "error: $SRC not found"; exit 1; }

# Preflight: is the relay up?
if ! lsof -nP -iTCP:"${RELAY##*:}" -sTCP:LISTEN >/dev/null 2>&1; then
  echo "warning: nothing is listening on ${RELAY} — start the relay first:"
  echo "  cargo run --manifest-path parcel21-protocol/relay/Cargo.toml"
fi

echo "Generating patched demo: $OUT"
cat > "$OUT" <<EOF
#!/usr/bin/env bash
# AUTO-GENERATED by integration/run.sh — demo.sh patched to deliver consignments over Parcel21.
PARCEL21_RELAY="\${PARCEL21_RELAY:-$RELAY}"
PARCEL21_CLIENT="$CLIENT"
PARCEL21_SANDBOX="$SANDBOX"
parcel21_deliver() {
  local send_data="\$1" rcpt_data="\$2" consignment="\$3"
  echo "  [parcel21] delivering \$consignment over Nostr -> \$PARCEL21_RELAY"
  ( cd "\$PARCEL21_CLIENT" && npx tsx scripts/rgb-e2e.ts \\
      --consignment "\$PARCEL21_SANDBOX/\$send_data/\$consignment" \\
      --out "\$PARCEL21_SANDBOX/\$rcpt_data/\$consignment" \\
      --no-validate --relay "\$PARCEL21_RELAY" ) \\
    || _die "[parcel21] consignment delivery failed"
}
EOF

# Append the rest of demo.sh (minus its shebang), swapping the cp hop for our delivery and
# raising the indexer-sync timeout (amd64 electrs under arm64 emulation is slow to sync).
tail -n +2 "$SRC" \
  | sed -e 's#_trace cp {"$send_data","$rcpt_data"}/"$CONSIGNMENT"#parcel21_deliver "$send_data" "$rcpt_data" "$CONSIGNMENT"#' \
        -e 's/^TIMEOUT=100$/TIMEOUT=600/' \
        -e 's/netcat -w1/nc -w 5/' \
  >> "$OUT"

# The demo's bash sync-check polls electrs over raw netcat/nc, which does not work on this host
# (GNU netcat in PATH) and electrs (amd64 under arm64 emulation) doesn't answer raw socket queries
# anyway — though rgb-cmd's own Rust electrum client works fine against it. Replace the bash
# sync-check with a brief settle; electrs indexes regtest blocks in <1s internally.
python3 - "$OUT" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p).read()
stub = ('_wait_indexers_sync() {\n'
        '    echo "  [parcel21] electrs settle (bash netcat sync-check bypassed; rgb-cmd syncs itself)"\n'
        '    sleep 8\n'
        '}')
s2, n = re.subn(r'_wait_indexers_sync\(\) \{.*?\n\}', stub, s, count=1, flags=re.S)
if n != 1:
    sys.stderr.write("warning: could not stub _wait_indexers_sync\n")
open(p, 'w').write(s2)
PY

# Sanity: confirm the swap happened and the cp is gone.
if grep -q 'parcel21_deliver "$send_data"' "$OUT" && ! grep -q '_trace cp {"$send_data"' "$OUT"; then
  echo "Patch OK: consignment hop now goes over Parcel21."
else
  echo "error: patch did not apply cleanly"; exit 1
fi

echo "Running rgb-sandbox scenario $SCENARIO with Parcel21 delivery…"
echo "========================================================================"
cd "$SANDBOX"
bash "$OUT" -s "$SCENARIO"
